#
# Module manifest for module 'tftools'
#
# Generated by: Roberth Strand
#
# Generated on: 11.07.2020
#

@{
    RootModule        = 'tftools.psm1'

    ModuleVersion     = '0.3.6'
    GUID              = '92a401a3-d16f-4bb5-89e5-19e2259e63db'

    Author            = 'Roberth Strand'
    CompanyName       = 'robstr.dev'

    Copyright         = 'tftools is licensed under the GNU General Public License v3.0'

    Description       = 'PowerShell tools for working with Terraform'

    FunctionsToExport = @("Install-Terraform", "Remove-Terraform", "Set-TerraformVersion", "Get-TerraformVersion")
    CmdletsToExport   = ''
    VariablesToExport = ''
    AliasesToExport   = @("itf", "rtf", "gtfv", "stfv")
    PrivateData       = @{
        PSData = @{
            Tags         = @("Terraform")
            ProjectUri   = 'https://github.com/roberthstrand/tftools'
            ReleaseNotes = 'https://github.com/roberthstrand/tftools/releases'
        }
    }

    HelpInfoURI       = 'https://github.com/roberthstrand/tftools/blob/master/docs/index.md'
}


